cybersec_clickhouse:
  target: prod
  outputs:
    prod:
      type: clickhouse
      schema: analytics
      host: "{{ env_var('CLICKHOUSE_HOST', 'zkddrg7t39.us-west-2.aws.clickhouse.cloud') }}"
      port: 8443
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: true